### ISSUE TITLE
Plugin failed when no {port_specs}

### ISSUE THREAD

**Issue by jeanparpaillon** [blt/port_compiler#18]
When declaring the pc plugin in rebar.config without any {port_specs}, the compile task fails

Example:
rebar.config:
{plugins, [pc]}.

Run rebar3 compile

**Comment by ghost** [comment]
I failed to reproduce this with 1.3.0 and 1.4.0. What else is needed to provoke a crash? Tested with no sources, just Erlang sources, and Erlang plus C sources.

**Comment by ghost** [comment]
@jeanparpaillon, ping?

**Comment by ghost** [comment]
Closing, @jeanparpaillon feel free to reopen if the issue persists.
