### ISSUE TITLE
rebar2 sync

### ISSUE THREAD

**Issue by ghost** [blt/port_compiler#22]
Cross compile support, clang compile commands db, and $CXX linking fixes are missing and have to be merged from rebar2.

**Comment by tuncer** [comment]
ping?

**Comment by blt** [comment]
Oh geez, sorry Tuncer. I haven't had a chance to work on the port_compiler
in quite a while.

**Comment by tuncer** [comment]
The plugin should be low maintenance, but a sync of all changes to rebar2's port_compiler would be great.

**Comment by blt** [comment]
I don't have spare time to work on port_compiler and won't for the foreseeable future. I've added you as a collaborator to this project.

**Comment by tuncer** [comment]
To sync port_compiler, we need to bring over the cross-compiler changes in rebar_util:word_size/0 as well. @tsloughter, can you pull the following diff into rebar_api.erl? The sync will bring Tony Rogval's cross-compiler patch, OS X fixes and Linux multilib (32bit+64bit userland) fixes.

```
$ cd rebar
$ git diff 54a7242...e1f7e6a src/rebar_utils.erl
```
https://github.com/rebar/rebar/compare/54a7242...e1f7e6a#diff-4911aac58108500dc420c518f45cb8fc

**Comment by tuncer** [comment]
Or alternatively, if you think the rebar_api.erl change is too invasive, maybe port_compiler should carry that code and, if possible, reuse rebar_api:wordsize/0 if possible.

**Comment by ghost** [comment]
Here's the patch: #25. Closing ticket.
