### ISSUE TITLE
Dead code and missing feature

### ISSUE THREAD

**Issue by ghost** [blt/port_compiler#26]
@tsloughter, @blt, has -D support been ditched altogether and, if so, deliberately?

If that's the case, then the following dead code should be removed. Otherwise, the function can be updated with a one line diff, but I don't know what replaced xconf.

https://github.com/blt/port_compiler/blob/9df79cd4409489ca9f1e8e6aeb2f74c272695ce3/src/pc_port_env.erl#L165-L169:

```
get_defines(_State) ->
    %% RawDefines = rebar_config:get_xconf(Config, defines, []),
    RawDefines = [], %% TODO: I'm not sure what this was...
    Defines = string:join(["-D" ++ D || D <- RawDefines], " "),
    [{"ERL_CFLAGS", "$ERL_CFLAGS " ++ Defines}].
```

**Comment by tuncer** [comment]
ping?

**Comment by tuncer** [comment]
ping?

**Comment by tuncer** [comment]
ping?
