### ISSUE TITLE
Error with new version

### ISSUE THREAD

**Issue by dlameri** [blt/port_compiler#44]
I'm using ejabberd, that uses fast_tls, that depends on pc.

After the new version 1.7.0 and 1.7.1, it broke. It was working with 1.6.0.

Do you have any idea what could be happening and how can i handle it?

===> Fetching pc ({pkg,<<"pc">>,<<"1.7.1">>})
===> Downloaded package, caching at /Users/dimitri.lameri/.cache/rebar3/hex/default/packages/pc-1.7.1.tar
===> Compiling pc
===> Compiling cache_tab
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
** (Mix) Could not compile dependency :cache_tab, "/Users/dimitri.lameri/.mix/rebar3 bare compile --paths "/Users/dimitri.lameri/Development/Projects/Mercurio/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile cache_tab", update it with "mix deps.update cache_tab" or clean it with "mix deps.clean cache_tab"

**Comment by fbernier** [comment]
duplicate of #43

**Comment by dlameri** [comment]
I'll close since it's duplicated
