### ISSUE TITLE
Update port_compiler to support OTP 27.0-rc2 by avoiding code:lib_dir/2

### ISSUE THREAD

**Issue by badlop** [blt/port_compiler#79]
In Erlang/OTP 27.0-rc2, `code:lib_dir/2` was marked as deprecated: 
https://erlang.org/documentation/doc-15.0-rc2/doc/deprecations.html#otp-27

And port_compiler uses that deprecated function in https://github.com/blt/port_compiler/blob/3c621624a289652ecc8e5d696558ec65e32ace27/src/pc_port_env.erl#L190

BTW, this warning crashes compilation completely, because port_compiler has the erlang option `warnings_as_errors` enabled in
https://github.com/blt/port_compiler/blob/3c621624a289652ecc8e5d696558ec65e32ace27/rebar.config#L13

The usage of that function was recently removed in rebar3 itself: https://github.com/erlang/rebar3/commit/17f6861c1540d8e4df586f29cb2d4e490e8f4bb7

It would be great to update port_compiler to work with OTP 27.0-rc2

**Comment by tsloughter** [comment]
Thanks. I've created https://github.com/blt/port_compiler/pull/80 and will merge+release today.

**Comment by badlop** [comment]
Thanks!

By the way, Erlang/OTP 27.0-rc3 was released recently. I've tested your `otp-27` branch, and it allows compiling port_compile perfectly :)

Do you plan to publish it anytime soon, so we can prepare and release other dependencies before the final OTP 27 gets released?

**Comment by gonzalobf** [comment]
Hey @badlop,

@tsloughter has deployed a new version a few hours ago so I think you can close the issue. It works perfectly fine for me.

**Comment by badlop** [comment]
Yes, it works great, thanks!
