### ISSUE TITLE
Drop "-g" flag from default options to reduce shared lib size

### ISSUE THREAD

**Issue by Zabrane** [blt/port_compiler#83]
Hi @tsloughter 

Would it be possible to drop `-g` flag from [pc_port_env.erl](https://github.com/blt/port_compiler/blob/master/src/pc_port_env.erl#L238-L240)?

Keeping `-g` in the default settings leads to super large `.so`. 

Here in a NIF example (cuckoo hashing):
```bash
# with "-g"
priv/cuckoo_hash.so -> 6.8M

# without "-g"
priv/cuckoo_hash.so -> 1.4M
```

If one wants to add debugging symbols, `CFLAGS + LDFLAGS` are there...thanks to `port_compiler`.

Many thanks
/Z

**Comment by tsloughter** [comment]
I'd be fine with that. Can you send a PR? Then we'll want to let it wait for a day or two for comment.

**Comment by Zabrane** [comment]
> I'd be fine with that. Can you send a PR? Then we'll want to let it wait for a day or two for comment.

Done.
